# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jan Jongboom's blog
description: > # this means to ignore newlines until "baseurl:"
  This blog is the central collection of my ramblings over the years, gathered
  from various sources. Everything from .NET to web dev to IoT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.janjongboom.com" # the base hostname & protocol for your site
twitter_username: janjongboom
github_username:  janjongboom

# Build settings
markdown: kramdown
paginate: 10
gems: [ jekyll-paginate ]
kramdown:
    input: GFM
